/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardMerchantRouteImport } from './routes/_authenticated/dashboard.merchant'
import { Route as AuthenticatedDashboardGmailRouteImport } from './routes/_authenticated/dashboard.gmail'
import { Route as AuthenticatedDashboardDriveRouteImport } from './routes/_authenticated/dashboard.drive'
import { Route as AuthenticatedDashboardCalendarRouteImport } from './routes/_authenticated/dashboard.calendar'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardGmailComposeRouteImport } from './routes/_authenticated/dashboard.gmail.compose'
import { Route as AuthenticatedDashboardGmailMessageIdRouteImport } from './routes/_authenticated/dashboard.gmail.$messageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMerchantRoute =
  AuthenticatedDashboardMerchantRouteImport.update({
    id: '/merchant',
    path: '/merchant',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGmailRoute =
  AuthenticatedDashboardGmailRouteImport.update({
    id: '/gmail',
    path: '/gmail',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDriveRoute =
  AuthenticatedDashboardDriveRouteImport.update({
    id: '/drive',
    path: '/drive',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarRoute =
  AuthenticatedDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGmailComposeRoute =
  AuthenticatedDashboardGmailComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedDashboardGmailRoute,
  } as any)
const AuthenticatedDashboardGmailMessageIdRoute =
  AuthenticatedDashboardGmailMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => AuthenticatedDashboardGmailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/drive': typeof AuthenticatedDashboardDriveRoute
  '/dashboard/gmail': typeof AuthenticatedDashboardGmailRouteWithChildren
  '/dashboard/merchant': typeof AuthenticatedDashboardMerchantRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/gmail/$messageId': typeof AuthenticatedDashboardGmailMessageIdRoute
  '/dashboard/gmail/compose': typeof AuthenticatedDashboardGmailComposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/drive': typeof AuthenticatedDashboardDriveRoute
  '/dashboard/gmail': typeof AuthenticatedDashboardGmailRouteWithChildren
  '/dashboard/merchant': typeof AuthenticatedDashboardMerchantRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/gmail/$messageId': typeof AuthenticatedDashboardGmailMessageIdRoute
  '/dashboard/gmail/compose': typeof AuthenticatedDashboardGmailComposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/_authenticated/dashboard/drive': typeof AuthenticatedDashboardDriveRoute
  '/_authenticated/dashboard/gmail': typeof AuthenticatedDashboardGmailRouteWithChildren
  '/_authenticated/dashboard/merchant': typeof AuthenticatedDashboardMerchantRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/gmail/$messageId': typeof AuthenticatedDashboardGmailMessageIdRoute
  '/_authenticated/dashboard/gmail/compose': typeof AuthenticatedDashboardGmailComposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/drive'
    | '/dashboard/gmail'
    | '/dashboard/merchant'
    | '/dashboard/settings'
    | '/api/google/callback'
    | '/dashboard/'
    | '/dashboard/gmail/$messageId'
    | '/dashboard/gmail/compose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/drive'
    | '/dashboard/gmail'
    | '/dashboard/merchant'
    | '/dashboard/settings'
    | '/api/google/callback'
    | '/dashboard'
    | '/dashboard/gmail/$messageId'
    | '/dashboard/gmail/compose'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/calendar'
    | '/_authenticated/dashboard/drive'
    | '/_authenticated/dashboard/gmail'
    | '/_authenticated/dashboard/merchant'
    | '/_authenticated/dashboard/settings'
    | '/api/google/callback'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/gmail/$messageId'
    | '/_authenticated/dashboard/gmail/compose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/merchant': {
      id: '/_authenticated/dashboard/merchant'
      path: '/merchant'
      fullPath: '/dashboard/merchant'
      preLoaderRoute: typeof AuthenticatedDashboardMerchantRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gmail': {
      id: '/_authenticated/dashboard/gmail'
      path: '/gmail'
      fullPath: '/dashboard/gmail'
      preLoaderRoute: typeof AuthenticatedDashboardGmailRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/drive': {
      id: '/_authenticated/dashboard/drive'
      path: '/drive'
      fullPath: '/dashboard/drive'
      preLoaderRoute: typeof AuthenticatedDashboardDriveRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendar': {
      id: '/_authenticated/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gmail/compose': {
      id: '/_authenticated/dashboard/gmail/compose'
      path: '/compose'
      fullPath: '/dashboard/gmail/compose'
      preLoaderRoute: typeof AuthenticatedDashboardGmailComposeRouteImport
      parentRoute: typeof AuthenticatedDashboardGmailRoute
    }
    '/_authenticated/dashboard/gmail/$messageId': {
      id: '/_authenticated/dashboard/gmail/$messageId'
      path: '/$messageId'
      fullPath: '/dashboard/gmail/$messageId'
      preLoaderRoute: typeof AuthenticatedDashboardGmailMessageIdRouteImport
      parentRoute: typeof AuthenticatedDashboardGmailRoute
    }
  }
}

interface AuthenticatedDashboardGmailRouteChildren {
  AuthenticatedDashboardGmailMessageIdRoute: typeof AuthenticatedDashboardGmailMessageIdRoute
  AuthenticatedDashboardGmailComposeRoute: typeof AuthenticatedDashboardGmailComposeRoute
}

const AuthenticatedDashboardGmailRouteChildren: AuthenticatedDashboardGmailRouteChildren =
  {
    AuthenticatedDashboardGmailMessageIdRoute:
      AuthenticatedDashboardGmailMessageIdRoute,
    AuthenticatedDashboardGmailComposeRoute:
      AuthenticatedDashboardGmailComposeRoute,
  }

const AuthenticatedDashboardGmailRouteWithChildren =
  AuthenticatedDashboardGmailRoute._addFileChildren(
    AuthenticatedDashboardGmailRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardCalendarRoute: typeof AuthenticatedDashboardCalendarRoute
  AuthenticatedDashboardDriveRoute: typeof AuthenticatedDashboardDriveRoute
  AuthenticatedDashboardGmailRoute: typeof AuthenticatedDashboardGmailRouteWithChildren
  AuthenticatedDashboardMerchantRoute: typeof AuthenticatedDashboardMerchantRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardCalendarRoute: AuthenticatedDashboardCalendarRoute,
    AuthenticatedDashboardDriveRoute: AuthenticatedDashboardDriveRoute,
    AuthenticatedDashboardGmailRoute:
      AuthenticatedDashboardGmailRouteWithChildren,
    AuthenticatedDashboardMerchantRoute: AuthenticatedDashboardMerchantRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
